### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by JuPrgn** [Facthunder/cppcheck#12]
Thank you for this image ! 

Do you plan to update Cppcheck ? I can see that your active branch 2.0 failed some time ago.

Cppcheck versions after 1.9 can take `.cppcheck` project configuration as command line parameter.

**Comment by begarco** [comment]
Hi @JuPrgn 

Yes it is planed to be released soon.

**Comment by JuPrgn** [comment]
Great thank you ! 

Pour info ça demande beaucoup d'efforts pour construire ce genre d'image ? Je configure actuellement une pipeline gitlab pour mes projets en utilisant des images du hub mais j'aurai probablement besoin d'en faire des spécifiques. Je débute avec docker et je n'ai pas encore tout compris sur le fonctionnement.
