### ISSUE TITLE
Image update

### ISSUE THREAD

**Issue by emalras** [Facthunder/cppcheck#19]
Hi,

Thank you for the image,

Did you plan to update the image to the new cppcheck 2.4.1 version?

Thanks in advance!

**Comment by begarco** [comment]
Hi @emalras 

The new version has been released, feel free to contribute to this project ;)

Regards,
Ben

**Comment by emalras** [comment]
Hi @begarco, 

Many thanks for the fast update!

Best Regards,

Enrique
